### ISSUE TITLE
סיום משמרת עם פידבק המתנדבים

### ISSUE THREAD

**Issue by Ben-Tu** [eranhd/Anti-Drug-Jerusalem#26]
יש לבצע פעולת לחצן סיום משמרת כך שיפתח דף סיום משמרת שם ניתן למתנדבים לתת פידבק על המשמרת

**Comment by eranhd** [comment]
בכניסה שוב לאפליקציה בלי לסיים מ שמרת העמוד לא עובד, הטעינה לפיירבייס לא מתבצעת
