### ISSUE TITLE
לתקן: כשיוצאים מהאפליקציה כל המידע נמחק

### ISSUE THREAD

**Issue by elitehadaroz** [eranhd/Anti-Drug-Jerusalem#35]
צריך לשנות שהמידע ישמר גם לאחר שנצא/נרענן את האפליקציה

**Comment by eranhd** [comment]
אני סוגר כי כרגע אני לא נותן אפשרות של רענון האפליקציה מהAPK. אני לא חושב שזה יהיה נכון שיוכלו להכנס בכלל לאפליקציה ישר לעמוד מסויים  ולא יעברו דרך העמוד אוטנטיקציה
