### ISSUE TITLE
Mission 3 - SRS: Feedback

### ISSUE THREAD

**Issue by YaakovHatam** [eranhd/Anti-Drug-Jerusalem#4]
## TODO:
- Please attach here the Client review.

## סיכום פגישתנו:
יש מוצר ברור, סיכונים ברורים, פגישות טובות עם הלקוח

**Comment by elitehadaroz** [comment]
[clientReview.docx](https://github.com/eranhd/Anti-Drug-Jerusalem/files/942839/clientReview.docx)
@kob-e
